version: '3.8'

services:
  # Redis service for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: llm-summarizer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - llm-summarizer-network

  # LLM Summarizer API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Usa la etapa de desarrollo con --reload
    container_name: llm-summarizer-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    # Healthcheck desactivado para desarrollo (descomentar para producción)
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/v1/healthz"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - llm-summarizer-network
    volumes:
      - ./app:/app/app:ro  # Monta el código fuente para hot reload
      - ./logs:/app/logs

  # Redis Commander for Redis management (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: llm-summarizer-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    depends_on:
      - redis
    networks:
      - llm-summarizer-network
    profiles:
      - tools

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: llm-summarizer-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - llm-summarizer-network
    profiles:
      - production

volumes:
  redis_data:
    driver: local

networks:
  llm-summarizer-network:
    driver: bridge
