version: '3.8'

services:
  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: llm-summarizer-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - llm-dev-network

  # Redis Commander for development
  redis-commander-dev:
    image: rediscommander/redis-commander:latest
    container_name: llm-summarizer-redis-commander-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis-dev:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=dev123
    depends_on:
      - redis-dev
    networks:
      - llm-dev-network

volumes:
  redis_dev_data:
    driver: local

networks:
  llm-dev-network:
    driver: bridge
